### ISSUE TITLE
[BUG] -webkit-text-stroke misaligned with the text

### ISSUE THREAD

**Issue by Mapaler** [yorickshan/html2canvas-pro#22]
Please make sure you are testing with the latest [release of html2canvas-pro](https://github.com/yorickshan/html2canvas-pro/releases). 
Old versions are not supported and issues reported for them will be closed.

# Please follow the general troubleshooting steps first:

- [x] You are using the latest [version](https://github.com/yorickshan/html2canvas-pro/releases)
- [x] You are testing using the non-minified version of html2canvas-pro and checked any potential issues reported in the console

### Bug reports:

[-webkit-text-stroke](https://developer.mozilla.org/zh-CN/docs/Web/CSS/-webkit-text-stroke)  Although it is not yet a W3C standard, it is generally supported by browsers.

![firefox_4000日1队全奖励_-_P D_1P_Formation_Maker_—_Firefox_Deve_0236](https://github.com/user-attachments/assets/981aa1c3-d3dc-45bd-b34c-0fa61c0f4601)

### Specifications:

 * html2canvas-pro version tested with: 1.5.6
 * Browser & version: Firefox v129
 * Operating system: Win10

**Comment by yorickshan** [comment]
fixed in v1.5.8

**Comment by Mapaler** [comment]
![firefox_Firefox_Developer_Edition_0316](https://github.com/user-attachments/assets/8fb7fa82-2b3f-40ba-b839-4794082b4294)
```html
<!DOCTYPE html>
<html>
<head>
  <style>
    ul {
      display: inline-flex;
      list-style-type: none;
    }

    li {
      color: red;
      font-size: 20px;
      -webkit-text-stroke: 1px blue;
    }

    canvas {
      border: 1px solid black;
    }

  </style>
  <!--<script src="node_modules/@html2canvas/html2canvas/dist/html2canvas.min.js"></script>-->
  <script src="node_modules/html2canvas-pro/dist/html2canvas-pro.min.js"></script>
</head>

<body>
  <ul>
    <li>Item 1</li>
    <li>Item 2</li>
    <li>Item 3</li>
  </ul>
  <button id="capture">Capture</button>
  <script>
    document.getElementById('capture').addEventListener('click', function () {
      [...document.body.querySelectorAll("canvas")].forEach(ca=>ca.remove());
      html2canvas(document.body).then(function (canvas) {
        document.body.appendChild(canvas);
      });
    });
  </script>
</body>
</html>
```

**Comment by yorickshan** [comment]
<!DOCTYPE html>
<html>

<head>
  <style>
    ul {
      display: inline-flex;
      list-style-type: none;
    }

    li {
      color: red;
      font-size: 20px;
      -webkit-text-stroke: 1px blue;
    }

    canvas {
      border: 1px solid black;
    }
  </style>
  
  <script src="https://cdn.jsdelivr.net/npm/html2canvas-pro@1.5.8/dist/html2canvas-pro.min.js"></script>
</head>

<body>
  <ul>
    <li>Item 1</li>
    <li>Item 2</li>
    <li>Item 3</li>
  </ul>
  <button id="capture">Capture</button>
  <script>
    document.getElementById('capture').addEventListener('click', function () {
      [...document.body.querySelectorAll("canvas")].forEach(ca => ca.remove());
      html2canvas(document.body).then(function (canvas) {
        document.body.appendChild(canvas);
      });
    });
  </script>
</body>

</html>

**Comment by Shonagon-Sei** [comment]
![Image](https://github.com/user-attachments/assets/308a4955-fc0e-4ca1-be3c-65b75081154e)

I'm using 1.5.8 and still have this issue
